### ISSUE TITLE
How to build this?

### ISSUE THREAD

**Issue by songbin** [ragingwind/libpthread#1]
I cannot find 'README' . now,I meet some trouble when trying to compile this project.
1.I cannot find 'Makeconf' file
2.I cannot find '../Rules' folder

3.for issue 1,I try to rename 'Makeconfig' to 'Makeconf',and move it to "../" ,after this ,It will show "**\* The header file `/pthread.h' is required, but not provided, by
**\* this configuration. Please report this to the maintainer.
"

I want to know where is 'README' . Thanks very much if any help.

**Comment by chriscz** [comment]
Take a look at where it was cloned from  http://git.savannah.gnu.org/cgit/hurd/libpthread.git/.

Alternatively, consider looking at `musl`, which is an alternative implementation of libc (including libpthread) https://www.musl-libc.org/
